package com.opencode.multilensipcam

import android.util.Range

object WebControlStates {
    fun buildFromSelections(
        versionName: String,
        versionCode: Long,
        versionLabel: String,
        repository: CameraLensRepository,
        streaming: Boolean,
        cameraOptions: List<CameraLensOption>,
        selectedCameraOption: CameraLensOption?,
        capabilities: CameraCapabilities?,
        selectedOutputSize: android.util.Size?,
        manualResolutionEnabled: Boolean,
        fpsOptions: List<Int>,
        selectedFps: Int?,
        unlimitedFpsSelected: Boolean,
        qualityValue: Int,
        zoomRange: Range<Float>?,
        runtimeControls: NativeRuntimeControlValues?,
        selectedFocusMode: FocusMode,
        focusDistanceSupported: Boolean,
        previewAdjustment: PreviewAdjustment,
        selectedJpegPipeline: MjpegPipeline,
        mjpegFullSize: Boolean,
        videoOverlayEnabled: Boolean,
        videoOverlaySize: Int,
        rtspUrl: String,
        rtspAvailable: Boolean,
        verifiedCameraOptions: List<WebOptionItem>,
        fallbackSelectedCameraLabel: String?,
        audioSupported: Boolean,
        audioPermissionGranted: Boolean,
        audioEnabled: Boolean,
        audioRunning: Boolean,
        audioClients: Int,
        audioUrl: String,
        audioStatus: String
    ): WebControlState {
        val exposureRange = capabilities?.exposureCompensationRange
        val selectedCameraKey = selectedCameraOption?.let(repository::controlKeyFor)
        val selectedCameraLabel = verifiedCameraOptions.firstOrNull { it.value == selectedCameraKey }?.label
            ?: fallbackSelectedCameraLabel

        return build(
            versionName = versionName,
            versionCode = versionCode,
            versionLabel = versionLabel,
            streaming = streaming,
            cameraOptions = cameraOptions.map { WebOptionItem(value = repository.controlKeyFor(it), label = it.label) },
            selectedCameraLabel = selectedCameraLabel,
            selectedCameraKey = selectedCameraKey,
            resolutionOptions = capabilities?.let(repository::listSelectableSizes)?.map(repository::sizeLabel).orEmpty(),
            selectedResolution = selectedOutputSize?.let(repository::sizeLabel),
            manualResolutionEnabled = manualResolutionEnabled,
            manualResolutionWidth = selectedOutputSize?.width,
            manualResolutionHeight = selectedOutputSize?.height,
            fpsOptions = fpsOptions,
            selectedFps = selectedFps,
            unlimitedFpsSupported = capabilities != null && repository.chooseUnlimitedFpsRange(capabilities) != null,
            unlimitedFpsSelected = unlimitedFpsSelected,
            qualityRange = StreamControlOptions.qualityOptions.first()..StreamControlOptions.qualityOptions.last(),
            qualityValue = qualityValue,
            zoomRange = zoomRange,
            zoomValue = runtimeControls?.zoomRatio,
            focusSupported = capabilities?.let(repository::hasManualFocus) == true,
            focusMode = selectedFocusMode,
            focusDistanceSupported = focusDistanceSupported,
            focusDistanceMax = if (focusDistanceSupported) capabilities?.minimumFocusDistance else null,
            focusDistanceValue = if (focusDistanceSupported) runtimeControls?.focusDistance else null,
            torchSupported = capabilities?.flashAvailable == true,
            torchEnabled = runtimeControls?.torchEnabled == true,
            videoOverlayEnabled = videoOverlayEnabled,
            videoOverlaySize = videoOverlaySize,
            exposureRange = exposureRange?.let { it.lower..it.upper },
            exposureValue = runtimeControls?.exposureCompensation ?: 0,
            previewRotation = previewAdjustment.rotation,
            previewScale = previewAdjustment.scale,
            previewStretchX = previewAdjustment.stretchX,
            previewStretchY = previewAdjustment.stretchY,
            selectedJpegPipeline = selectedJpegPipeline,
            mjpegFullSize = mjpegFullSize,
            rtspUrl = rtspUrl,
            rtspAvailable = rtspAvailable,
            verifiedCameraOptions = verifiedCameraOptions,
            audioSupported = audioSupported,
            audioPermissionGranted = audioPermissionGranted,
            audioEnabled = audioEnabled,
            audioRunning = audioRunning,
            audioClients = audioClients,
            audioUrl = audioUrl,
            audioStatus = audioStatus
        )
    }

    fun build(
        versionName: String,
        versionCode: Long,
        versionLabel: String,
        streaming: Boolean,
        cameraOptions: List<WebOptionItem>,
        selectedCameraLabel: String?,
        selectedCameraKey: String?,
        resolutionOptions: List<String>,
        selectedResolution: String?,
        manualResolutionEnabled: Boolean,
        manualResolutionWidth: Int?,
        manualResolutionHeight: Int?,
        fpsOptions: List<Int>,
        selectedFps: Int?,
        unlimitedFpsSupported: Boolean,
        unlimitedFpsSelected: Boolean,
        qualityRange: IntRange,
        qualityValue: Int,
        zoomRange: Range<Float>?,
        zoomValue: Float?,
        focusSupported: Boolean,
        focusMode: FocusMode,
        focusDistanceSupported: Boolean,
        focusDistanceMax: Float?,
        focusDistanceValue: Float?,
        torchSupported: Boolean,
        torchEnabled: Boolean,
        videoOverlayEnabled: Boolean,
        videoOverlaySize: Int,
        exposureRange: IntRange?,
        exposureValue: Int?,
        previewRotation: Int,
        previewScale: Float,
        previewStretchX: Float,
        previewStretchY: Float,
        selectedJpegPipeline: MjpegPipeline,
        mjpegFullSize: Boolean,
        rtspUrl: String,
        rtspAvailable: Boolean,
        verifiedCameraOptions: List<WebOptionItem>,
        audioSupported: Boolean,
        audioPermissionGranted: Boolean,
        audioEnabled: Boolean,
        audioRunning: Boolean,
        audioClients: Int,
        audioUrl: String,
        audioStatus: String
    ): WebControlState {
        return WebControlState(
            versionName = versionName,
            versionCode = versionCode,
            versionLabel = versionLabel,
            streaming = streaming,
            cameraOptions = cameraOptions,
            selectedCameraLabel = selectedCameraLabel,
            selectedCameraKey = selectedCameraKey,
            resolutionOptions = resolutionOptions,
            selectedResolution = selectedResolution,
            manualResolutionEnabled = manualResolutionEnabled,
            manualResolutionWidth = manualResolutionWidth,
            manualResolutionHeight = manualResolutionHeight,
            fpsOptions = fpsOptions,
            selectedFps = selectedFps,
            unlimitedFpsSupported = unlimitedFpsSupported,
            unlimitedFpsSelected = unlimitedFpsSelected,
            qualityMin = qualityRange.first,
            qualityMax = qualityRange.last,
            qualityValue = qualityValue,
            zoomSupported = zoomRange != null,
            zoomMin = zoomRange?.lower,
            zoomMax = zoomRange?.upper,
            zoomValue = zoomValue,
            focusSupported = focusSupported,
            focusMode = focusMode.wireValue,
            focusDistanceSupported = focusDistanceSupported,
            focusDistanceMin = if (focusDistanceSupported) 0f else null,
            focusDistanceMax = if (focusDistanceSupported) focusDistanceMax else null,
            focusDistanceValue = if (focusDistanceSupported) focusDistanceValue else null,
            torchSupported = torchSupported,
            torchEnabled = torchEnabled,
            videoOverlayEnabled = videoOverlayEnabled,
            videoOverlaySizeMin = VIDEO_OVERLAY_SIZE_MIN_PERCENT,
            videoOverlaySizeMax = VIDEO_OVERLAY_SIZE_MAX_PERCENT,
            videoOverlaySizeValue = videoOverlaySize.coerceIn(VIDEO_OVERLAY_SIZE_MIN_PERCENT, VIDEO_OVERLAY_SIZE_MAX_PERCENT),
            exposureSupported = exposureRange != null,
            exposureMin = exposureRange?.first,
            exposureMax = exposureRange?.last,
            exposureValue = exposureValue,
            previewRotation = previewRotation,
            previewScale = previewScale,
            previewStretchX = previewStretchX,
            previewStretchY = previewStretchY,
            selectedJpegPipeline = selectedJpegPipeline.controlValue,
            mjpegFullSize = mjpegFullSize,
            rtspUrl = rtspUrl,
            rtspAvailable = rtspAvailable,
            verifiedCameraOptions = verifiedCameraOptions,
            audioSupported = audioSupported,
            audioPermissionGranted = audioPermissionGranted,
            audioEnabled = audioEnabled,
            audioRunning = audioRunning,
            audioStreaming = audioRunning,
            audioClients = audioClients,
            audioUrl = audioUrl,
            audioStatus = audioStatus
        )
    }
}
